name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /apps/staging/trainingportalfrontend

            # Reset repo to avoid conflicts
            git fetch origin main
            git reset --hard origin/main

            # Show latest commit deployed
            echo "Latest deployed commit:"
            git log -1 --oneline

            # Install & build
            rm -rf node_modules
            npm install
            npx vite build --mode production

            # Restart frontend
            pm2 delete frontend || true
            pm2 start "npx serve -s dist -l 8080" --name frontend
