name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /apps/staging/trainingportalfrontend
            git reset --hard HEAD
            git pull origin main
            npm install
            npx vite build --mode production
            pm2 restart frontend || pm2 serve dist 8080 --name frontend --spa --no-cache
